Add Pkl 0.26 features
apple/pkl-swift pull request #23
Opened 2024-06-24 12:30 UTC by holzensp

2024-06-26 05:06 UTC, bioball requested changes
Looking pretty good! Left some comments.

Also: I'm seeing some formatting issues. Can you run `swiftformat` on these changes?

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/PklEvaluatorSettings.swift
> +    /// address = "http://my.proxy.example.com:5080"
The syntax when using this would be more something like `let proxy: Proxy = .init(address: "http://foo.com")` (no equal sign).

But, I think it should be good enough to just provide a plain value as an example.

```suggestion
    /// "http://my.proxy.example.com:5080"
```

Same comment for `noProxy`.

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/PklEvaluatorSettings.swift
> +    /// The address must start with "http://", and cannot contain anything other than a host and an optional port.
```suggestion
    /// The address must start with `"http://"`, and cannot contain anything other than a host and an optional port.
```

2024-06-26 05:06 UTC, bioball commented on Tests/PklSwiftTests/EvaluatorTest.swift
> +        XCTAssert("\(err!)".contains(expected))
This is a little simpler:

```suggestion
        do {
            let evaluator = try await manager.newEvaluator(options: options)
            let _ = try await evaluator.evaluateOutputText(source: .uri("https://example.com")!)
            XCTFail("Should have thrown an error")
        } catch {
            XCTAssert("\(error)".contains(expected))
        }
```

2024-06-26 05:06 UTC, bioball commented on Tests/PklSwiftTests/EvaluatorTest.swift
> +                        noProxy: ["myhost.com:1337", "myotherhost.org:42"]))
Nit: we tend to prefer `.init` here.

Also: I think let's talk to localhost instead of making an outbound call to example.com, which is a DNS name. This picks a random port, which can lead to brittleness. Another option could be to copy what we do in pkl-go and [pick an open port](https://github.com/apple/pkl-go/blob/bc1573a652c925f44565982c37f6fd13f3a9937f/pkl/evaluator_test.go#L69-L87).

```suggestion
        options.http = .init(
                caCertificates: nil,
                proxy: .init(
                        address: "http://localhost:14172",
                        noProxy: ["myhost.com:1337", "myotherhost.org:42"]))
```

2024-06-26 05:06 UTC, bioball commented on Tests/PklSwiftTests/ProjectTest.swift
> +                http: nil
Can we add http to the test?

We'll need to define multiple tests, since the option got introduced in 0.26.

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorOptions.swift
> +        options.http = evaluatorSettings.http ?? http
This looks much better!

One nit: in terms of style, we follow the swift on server folks and use explicit `self`

```suggestion
        options.properties = evaluatorSettings.externalProperties ?? self.properties
        options.env = evaluatorSettings.env ?? self.env
        options.allowedModules = evaluatorSettings.allowedModules ?? self.allowedModules
        options.allowedResources = evaluatorSettings.allowedResources ?? self.allowedResources
        options.cacheDir = evaluatorSettings.noCache != nil ? nil : (evaluatorSettings.moduleCacheDir ?? self.cacheDir)
        options.rootDir = evaluatorSettings.rootDir ?? self.rootDir
        options.http = evaluatorSettings.http ?? self.http
```

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +}
This method should be memoized. It should probably also be defined as a method on the evaluator manager.

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +    process.arguments = Array(pklCommand.dropFirst()) + ["--version"]
```suggestion
    process.arguments = pklCommand + ["--version"]
```

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +/// Get the version of the `pkl-server` being used.
```suggestion
/// Get the version of the Pkl being used.
```

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +          let output = String(data: outputData, encoding: .ascii)?.split(separator: " "),
Although this probably wouldn't ever get us into trouble, Pkl writes with utf-8 encoding.

```suggestion
          let output = String(data: outputData, encoding: .utf8)?.split(separator: " "),
```

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +func getVersion() throws -> SemanticVersion {
Let's make this a private method? Do we want to commit to `SemanticVersion` being part of our public API?

In pkl-go, we have a `GetVersion()` that returns a string, and a private `getVersion()` that returns an internal semver struct.

2024-06-26 05:06 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +let supportedPklVersions = [
I see a test that uses this, but don't understand why this is here.

2024-06-26 08:43 UTC, stackoverflow approved these changes
LGTM

2024-06-26 08:43 UTC, stackoverflow commented on Tests/PklSwiftTests/EvaluatorTest.swift
> +                        noProxy: ["myhost.com:1337", "myotherhost.org:42"]))
We should pick an open port, otherwise this may lead to "sometimes works on my machine".

2024-06-26 14:24 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +    process.arguments = Array(pklCommand.dropFirst()) + ["--version"]
Oh, actually--bad suggestion, my bad.

2024-06-27 14:45 UTC, holzensp commented on Sources/PklSwift/EvaluatorManager.swift
> +}
Yes to memoization. I didn't put it inside the evaluator manager because it has no dependencies on any of its innards. I went back and forth on this, but I felt putting it into evaluator manager suggested it was a managed part; i.e. that you could use different evaluator versions in the same program.

2024-06-27 14:45 UTC, holzensp commented on Sources/PklSwift/EvaluatorManager.swift
> +let supportedPklVersions = [
Future proofing; having the tests automatically cover all supported cases. Happy to put this in the test, but I thought putting it next to the definitions of `pklVersion0_xx` would be safer.

2024-06-27 14:45 UTC, holzensp commented on Sources/PklSwift/EvaluatorOptions.swift
> +        options.http = evaluatorSettings.http ?? http
Have you found ways to mute IDE warnings? Having dozens of "'self' is unnecessary" warnings makes the code analysis borderline useless.

2024-06-27 14:45 UTC, holzensp commented on Tests/PklSwiftTests/EvaluatorTest.swift
> +                        noProxy: ["myhost.com:1337", "myotherhost.org:42"]))
Picking an open port leads to potential races :( There is no real "idea" solution here, I think. What about a reserved port that is not in use anymore (like `1`) or one that _should_ not be in use anymore (like `23`)?

2024-06-27 15:04 UTC, holzensp commented on Sources/PklSwift/EvaluatorManager.swift
> +}
Then again, memoization can probably best be done _inside_ the Evaluator Manager... I'll roll it in.

2024-06-27 16:42 UTC, holzensp commented on Tests/PklSwiftTests/ProjectTest.swift
> +                http: nil
I've made it conditional on the version.

2024-06-27 16:46 UTC, holzensp commented on Sources/PklSwift/EvaluatorManager.swift
> +func getVersion() throws -> SemanticVersion {
Rolled it into EvaluatorManager and let it return a `String`. Btw, it was already "internal" (as opposed to "public").

2024-06-27 17:02 UTC, bioball commented on Sources/PklSwift/EvaluatorManager.swift
> +}
The evaluator manager represents a child process. We don't do this yet, but at some point we should have a `newEvaluatorManagerWithCommand` constructor [like we do in go](https://pkg.go.dev/github.com/apple/pkl-go/pkl#NewProjectEvaluatorWithCommand).

For that reason, you can totally have multiple mangers, each with their own version, and that's also why the `GetVersion()` method is on the evalutor manager in Go: https://pkg.go.dev/github.com/apple/pkl-go/pkl#EvaluatorManager.

2024-07-02 04:59 UTC, bioball approved these changes
Just one comment, but approving to unblock.

Also: same comment as before; can you run `swiftformat` on this code before committing?

2024-07-02 04:59 UTC, bioball commented on Tests/PklSwiftTests/ProjectTest.swift
> +                address = "http://proxy.mock.example.com:1"
Same comment; for here and line 56: can we use `localhost` as the proxy address? `example.com` is a real domain.

2024-07-02 11:36 UTC, merged