Implement SPICE-0009 External Readers
apple/pkl-swift pull request #26
Opened 2024-09-25 21:10 UTC by HT154

[SPICE-0009](https://github.com/apple/pkl-evolution/pull/10)

2024-12-17 06:21 UTC, HT154 commented on Sources/MessagePack/Encoder/SingleValueEncodingContainer.swift
> +            self.storage.append(0b10010000)
File under: Swift behavior that caught me way off guard

2025-01-14 01:01 UTC, HT154 commented on Sources/MessagePack/Encoder/SingleValueEncodingContainer.swift
> +            try self.encode(bytes)
In Swift, empty arrays succeed for dynamic casting operations to other array types (`Array<T>() is Array<U> == true`). In order to correctly fall through for empty non-`UInt8` array an additional type comparison using `type(of:)` is required. For the `fallthrough` to work correctly this case must directly precede the `default` case.

2025-01-14 01:02 UTC, HT154 commented on Sources/MessagePack/Encoder/SingleValueEncodingContainer.swift
> +            encoder.codingPath = codingPath
Encoders are much simpler to debug when they tell you where they're at :)

2025-01-14 01:13 UTC, HT154 commented
This should be all set now! Probably best to merge after https://github.com/apple/pkl/pull/882 lands and Pkl 0.27.2 is published and added to CI.

2025-01-15 23:38 UTC, bioball requested changes
This mostly looks good! See comments.

Also: can you update the license headers here?

For new files, set year to 2025. For files that have been modified, set year to 2024-2025.

2025-01-15 23:38 UTC, bioball commented on Sources/PklSwift/MessageTransport.swift
> +            fatalError("Unreachable code")
```suggestion
            throw PklBugError.unknownMessage("Received unexpected message: \(messageType)")
```

2025-01-15 23:38 UTC, bioball commented on docs/modules/ROOT/pages/external-readers.adoc
> +@main struct Main {
```suggestion
import Foundation
import PklSwift

@main struct Main {
```

2025-01-15 23:38 UTC, bioball commented on Sources/MessagePack/Encoder/SingleValueEncodingContainer.swift
> +            try self.encode(bytes)
TIL!

2025-01-15 23:38 UTC, bioball commented on Sources/PklSwift/ExternalReaderClient.swift
> +    func handleInitializeModuleReaderRequest(request: InitializeModuleReaderRequest) async throws {
Unnecessary async; there's nothing being awaited here

```suggestion
    func handleInitializeModuleReaderRequest(request: InitializeModuleReaderRequest throws {
```

2025-01-15 23:38 UTC, bioball commented on Sources/PklSwift/ExternalReaderClient.swift
> +        async throws {
Same here re: unnecessary async

```suggestion
    func handleInitializeResourceReaderRequest(request: InitializeResourceReaderRequest) throws {
```

2025-01-16 21:42 UTC, bioball approved these changes
LGTM!

2025-01-17 10:29 UTC, stackoverflow approved these changes
Looks good!

2025-01-17 14:34 UTC, merged